### PR TITLE
Ensure proper order for obtaining credentials, assuming roles, using profiles

### LINKED ISSUE #4: Error getting creds when assuming role and using fallback credentials
Related issues:
* terraform-providers/terraform-provider-aws#8242
* terraform-providers/terraform-provider-aws#8052
* terraform-providers/terraform-provider-aws#6566
* terraform-providers/terraform-provider-aws#6424
* terraform-providers/terraform-provider-aws#5592
* terraform-providers/terraform-provider-aws#2420

Currently, session-derived credentials are obtained _after_ execution has passed the assume role logic.

**Currently** Session-derived creds _without_ profile:
```
GetSession()
    |
    |---> GetSessionOptions()
            |
            |---> GetCredentials()
            |       |
            |       |---> ASSUME ROLE (starting awsauth.go:233)
            |
            |--- SESSION-DERIVED CREDS OBTAINED, if no profile (session.go:49)
```

**Currently** Session-derived creds _with_ profile:
```
GetSession()
    |
    |---> GetSessionOptions()
    |       |
    |       |---> GetCredentials()
    |       |       |
    |       |       |---> ASSUME ROLE (starting awsauth.go:233)
    |       |
    |       |--- Profile set (session.go:59)
    |       
    |--- SESSION-DERIVED CREDS OBTAINED, if profile (session.go:94)
```

Specific resultant issue:
* On the `awsauth.go` path, you _cannot_ assume a role if your credentials come from a credential process. However, you _can_ assume a role if your credentials come from a shared credentials profile.

The error that you can expect to see:
```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider
```

### PR DESCRIPTION
**Pull request by YakDriver**
Fixes #4 

**Cleans up credential obtaining logic.**

NOTE: I contributed the [credential process provider](https://github.com/aws/aws-sdk-go/pull/2217) to the underlying AWS SDK Go.

Proposal:
* Ensure creds obtained (e.g., session-derived) _before_ attempting to assume role
* Update `GetCredentials()` contract so that creds are retrieved _and_ validated - simplifying logic in `GetSession()` and `GetSessionOptions()`.

Currently, the bug prevents fall-back creds (e.g., session-derived) from being used when assuming a role since session-derived creds are not obtained until _after_ the assume role logic. As a result, these circumstances will always result in failure to use credentials even when they are valid.

This PR fixes the bug.

In this PR, `GetCredentials()` has a new contract - it provides and validates credentials. Before, `GetCredentials()` would sometimes return unvalidated creds and sometimes validated creds. This meant that more error handling logic needed to be included in `GetSession()` and `GetSessionOptions()`. As part of validating creds, `GetCredentials()` now gets session-derived creds, if necessary, prior to assuming a role.

Related/possibly also fixed:
* terraform-providers/terraform-provider-aws#8242
* terraform-providers/terraform-provider-aws#8052
* terraform-providers/terraform-provider-aws#6566
* terraform-providers/terraform-provider-aws#6424
* terraform-providers/terraform-provider-aws#5592
* terraform-providers/terraform-provider-aws#2420
* terraform-providers/terraform-provider-aws#5251
* terraform-providers/terraform-provider-aws#5078
* terraform-providers/terraform-provider-aws#5018

### CODE REVIEW

**Comment by YakDriver** [comment]
In contrast to execution graph in issue #4, this is an updated graph.

**With this PR** Session-derived creds with or without profile:
```
GetSession()
    |
    |---> GetSessionOptions()
    |       |
    |       |---> GetCredentials()
    |       |       |
    |       |       |---> GetCredentialsFromSession() (call at awsauth.go:294)
    |       |       |
    |       |       |---> Assume role (starting awsauth.go:306)
```

**Comment by lorengordon** [comment]
This would be very handy, allowing us to use `credential_process` in the profile to retrieve a credential from a federated identity provider, and the `assume_role` block in the terraform provider config to switch role. Interpolation in the `assume_role` block reduces the number of profiles to manage on the system.

**Comment by max-rocket-internet** [comment]
@bflad can we get this reviewed and merged? It's a major problem for us also (https://github.com/terraform-providers/terraform-provider-aws/issues/8052)

**Comment by bsAdvanon** [comment]
I'm blocked by the same issues at the moment. Any ideas about when this could get merged?

**Comment by bsuv** [comment]
@radeksimko @grubernaut @bflad  ^^^

**Comment by kinghuang** [comment]
Is there any word on when this will be reviewed and merged? It doesn't look been any commit activity at all on this repo for months. I'm also impacted by https://github.com/terraform-providers/terraform-provider-aws/issues/8052.

**Comment by YakDriver** [comment]
¯\_(ツ)_/¯
I wish I knew.

**Comment by bflad** [comment]
Hi folks and thanks so much @YakDriver for taking this on. 👋 Sorry for the delays in getting this pull request reviewed. This one is on me for not leaving a comment here sooner. 🤕 

One of the major challenges that we have here is that this code has been inherited without much documentation and testing from when it progressed from Terraform Core (when providers lived in there) to the Terraform AWS Provider to this library (see also #2). This means that while the changes here might potentially work as expected, we have no basis for potential regressions either other than waiting for bug reports. 😖 Since my tenure in helping maintain the Terraform AWS Provider, changes to this logic were always problematic for someone's configuration. It would certainly be preferred to get this codebase out of its current rut though and for sure help to squash this bug as it is certainly creating a frustrating experience as noted here and in the provider issues.

Real briefly, the various ways to getting this out there given the current state of this library would be:

* After an in depth review of the physical code changes for an estimate of potential regressions in current behavior, accepting this, and forcing a major Terraform AWS Provider release so it can be used easily out in the wild under the guise that it may have introduced breaking behavior. The maintainers of the Terraform AWS Providers have not fully decided what version 3.0.0 will or should contain, so in full disclosure, those discussions would likely bottleneck this process. 
* Using the issue this is closing (#4) to capture user experience reports with custom build Terraform AWS Providers that use this update. To that end, providing a how-to guide to accomplish this might help everyone. I mention using the issue for this purpose because to a certain degree we do not want the pull request comments to get into non-code discussions if there are a lot of incoming reports.
* While I haven't personally looked too much into this due to priorities being elsewhere, I have a feeling we might be able to piggyback the testing implementation in #2 based on how the AWS Go SDK performs _its_ testing. Other than determining the implementation of these tests, the code itself might not be well suited for the decided testing framework, which could present its own problems. This discussion should probably occur in #2 rather than in here just to keep this particular code change's comments relevant.

We don't necessarily need to pick and choose _one_ of these options. In fact, agreeing/working on all fronts would likely ensure the best outcome for everyone.

Apologies again for the frustrating experience. If we could get some help/opinions on these items, hopefully we can push this forward in a constructive manner.

**Comment by lorengordon** [comment]
On the plus side, there are no (known) backwards breaking changes here, no syntax changes required in the user config. A bug is a bug, it gets reported then patched and released. An impacted user can easily pin their version in the meantime.

Totally agree tests around the credential handling would be helpful. Do you have any idea how you might want to see those tests setup?

**Comment by YakDriver** [comment]
I know it's anecdotal and practically useless but I did integration tests with every possible scenario I could think of, backwards and forwards, and could not find anything breaking with these changes.

As for @bflad's points:

1. I agree with @lorengordon that there are no _known_ breaking changes with this PR. However, any users affected by potential breaking changes should be weighed against the many users _known_ to be experiencing issues.
2. I can provide guidance on building binaries using the patch. This would probably be doable in the shortish-term.
3. My creating regression tests is probably not going to happen in the short-term. We'd all welcome help if someone is available. I agree that these would be very comforting to have.

**Comment by ianwsperber** [comment]
I'd like to chime in my support for the second point as an interim solution until a fix is released. If there were a simple-ish mechanism to run the provider with a custom binary I'd be happy to provide feedback after the fact on whether we've encountered any issues. I'm sure it'll be valuable to have in place long term, and it seems like a good baseline for getting feedback on the fix in lieu of regression tests.

**Comment by YakDriver** [comment]
If you would like to build Terraform and the AWS provider with this patch, I've created instructions on how to do it. It's a bit beyond the scope of a GitHub comment so please [check out the article on Medium](https://medium.com/@dirk.avery/building-terraform-from-source-with-a-patch-7050bdc4576c). Thanks @ianwsperber for being willing to try it out. Let me know if you have trouble with the instructions.

Post user experience reports on #4!

Leave comments specific to this PR's code changes here.

**Comment by ianwsperber** [comment]
@YakDriver My apologies, I have been and continue to be too busy to validate this myself. I just posted in a related issue to see if anyone else might be willing to validate your solution: https://github.com/terraform-providers/terraform-provider-aws/issues/8052

**Comment by timoguin** [comment]
I gave it a good try, but I've not been able to get everything to build properly. :(

**Comment by YakDriver** [comment]
@timoguin If you have specific problems, let me know in the article comments.

**Comment by mohrt** [comment]
I went around and around with a related problem today, hopefully this might help someone. Here are my config/credentials files:

> [default]
> aws_access_key_id = REMOVED
> aws_secret_access_key = REMOVED
> 
> [prod]
> aws_access_key_id = REMOVED
> aws_secret_access_key = REMOVED
> 
> [dev]
> 

(the empty [dev] role uses the [default])

> [profile default]
> region = us-west-2
> output = json
> role_arn = arn:aws:iam::<removed>:role/CrossAccount
> source_profile = prod
> 
> [profile prod]
> region=us-east-1
> output = json
> 
> [profile dev]
> region = us-west-2
> output = json
> role_arn = arn:aws:iam::<removed>:role/CrossAccount
> source_profile = prod

My terraform setup uses an s3 bucket to maintain the state file. The above works, however when I would copy the key/secret from the default profile and paste it into the (empty) dev profile, it would no longer assume the role and begin failing with "access denied" errors, because the s3 bucket was being accessed by the prod profile. Apparently this causes an internal ordering of events to incorrectly pick up the prod user instead of the dev CrossAccount role.

**Comment by mmack-innio** [comment]
Seeing the same issues, please merge :+1:

**Comment by aeschright** [comment]
Hi @YakDriver! I finally got enough unit test coverage together to go ahead with this PR and merged it to master. I checked the tests against your code and I think there's only one small change because the error type for missing credentials is different. Do you have time this week to rebase and make an update?

**Comment by YakDriver** [comment]
@aeschright Absolutely. Where do you want an update?

**Comment by aeschright** [comment]
`TestAWSGetCredentials_shouldErrorWhenBlank` and `TestAWSGetCredentials_shouldErrorWithInvalidEndpoint` will need to check for the correct error.

**Comment by YakDriver** [comment]
This is a work in progress. I'm headed out but this is the first shot. I will check it out tomorrow!

**Comment by YakDriver** [comment]
I had to change those two tests a little but I think they still capture what you're going for. Let me know if you want any other changes.

**Comment by aeschright** [comment]
Alright, let's do it! I'm going to merge this and test against the provider before I do a release.

**Comment by YakDriver** [comment]
Outstanding! 🤞

**Pull request merged**
